### ISSUE TITLE
Only first AnimationGroup seems to be imported

### ISSUE THREAD

**Issue by Vinc3r** [babylon-runtime/_r#24]
See this scene: https://codesandbox.io/s/github/Vinc3r/codesandbox-project/tree/master/BabylonJS/_runtime/git-reports/animationGroups?fontsize=14&hidenavigation=1&theme=dark

Only Cube animations are availabled, others are empties. When dragging the [glb file](https://github.com/Vinc3r/codesandbox-project/blob/master/BabylonJS/_runtime/git-reports/animationGroups/scene.glb?raw=true) into [sandbox](sandbox.babylonjs.com/) we can play every animations, so it's not from BJS or .glb

**Comment by Vinc3r** [comment]
_r.load seems to have the same behaviour

**Comment by BabylonRuntime** [comment]
Not related to the runtime, same result with BABYLON.SceneLoader, only the sandbox has the desired behavior and I don't think we should try to fix this
