### ISSUE TITLE
add TransformNode in filters

### ISSUE THREAD

**Issue by Vinc3r** [babylon-runtime/_r#3]
to allow use of the selector `_r("*:transformnode")` (useful for gltf imports, when a mesh with multimaterials is splitted into submeshes)

https://doc.babylonjs.com/api/classes/babylon.transformnode#getclassname

**Comment by fabsharp** [comment]
Test case please with gltf files and basic selector usage :D

**Comment by Vinc3r** [comment]
cornellBox.glb should do the trick: https://github.com/babylon-runtime/_r.assets/blob/master/cornellBox/exports/glb/cornellBox.glb

Example: on Blender, `cornellBox.000` is one object with 4 materials, once in glTF, the main object is converted in a transformNode, parent of one mesh per materials

![img](https://i.imgur.com/SWjRkIQ.png)
