### ISSUE TITLE
Under Chrome android, the loading percentage doesn't work

### ISSUE THREAD

**Issue by cstfan** [babylon-runtime/_r#32]
Under Chrome android, the loading percentage doesn't work, it displays NaN% instead.

![Screenshot_2020-03-05-10-53-11-388_com android chrome](https://user-images.githubusercontent.com/33685211/76002390-d2d77700-5f06-11ea-8694-7389d4464ce5.jpg)

http://3dmad.online.fr/WebGL/Steelcase_v0.9/index.html
But in private browsing mode there is no problem.

**Comment by fabsharp** [comment]
I can't reproduce the bug on my Chrome Android...

If it works in private browsing, may it come from an old version still in the cache ?

**Comment by cstfan** [comment]
I deleted the cache AND the data via application management, now it works.

![Screenshot_2020-03-05-18-37-26-338_com miui securitycenter](https://user-images.githubusercontent.com/33685211/76010195-cd802980-5f12-11ea-8299-5210b930f014.jpg)
